# 服务端口
server:
  port: 8003
spring:
  application:
    # 服务名
    name: service-vod
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  servlet:
    multipart:
      # 最大上传单个文件大小：默认1M
      # 最大置总上传的数据大小 ：默认10M
      max-file-size: 1024MB
      max-request-size: 1024MB
  cloud:
    nacos:
      discovery:
        # nacos服务地址
        server-addr: 127.0.0.1:8848

aliyun:
  vod:
    file:
      #阿里云 vod
      #不同的服务器，地址不同
      key-id: LTAI5tC13CSVHJeNjtuTtJuZ
      key-secret: cZa4gbRigJQr8F1b5H8O1rAgv5h7Nv

