#服务端口
server:
  port: 8002
#  #阿里云 OSS
#  #不同的服务器，地址不同
#  aliyun.oss.file.endpoint=your endpoint
#  aliyun.oss.file.keyid=your accessKeyId
#  aliyun.oss.file.keysecret=your accessKeySecret
#  #bucket可以在控制台创建，也可以使用java代码创建
spring:
  application:
#    服务名
    name: service-oss
#    环境设置：dev、test、prod
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        # nacos服务地址
        server-addr: 127.0.0.1:8848

#阿里云 OSS
#不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5tC13CSVHJeNjtuTtJuZ
      keysecret: cZa4gbRigJQr8F1b5H8O1rAgv5h7Nv
#      bucket可以在控制台创建，也可以使用java代码创建
      bucketname: 'edu-demo-oss'